.Dd April 1, 2013
.Dt libfdata 3
.Os libfdata
.Sh NAME
.Nm libfdata.h
.Nd Library to provide generic file data functions
.Sh LIBRARY
.Lb libfdata
.Sh SYNOPSIS
.In libfdata.h
.Pp
Support functions
.Ft const char *
.Fn libfdata_get_version "void"
.Pp
Error functions
.Ft void
.Fn libfdata_error_free "libfdata_error_t **error"
.Ft int
.Fn libfdata_error_fprint "libfdata_error_t *error, FILE *stream"
.Ft int
.Fn libfdata_error_sprint "libfdata_error_t *error, char *string, size_t size"
.Ft int
.Fn libfdata_error_backtrace_fprint "libfdata_error_t *error, FILE *stream"
.Ft int
.Fn libfdata_error_backtrace_sprint "libfdata_error_t *error, char *string, size_t size"
.Pp
Identifier functions
.Ft int
.Fn libfdata_identifier_initialize "libfdata_identifier_t **identifier, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_free "libfdata_identifier_t **identifier, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_from_byte_stream "libfdata_identifier_t *identifier, const uint8_t *byte_stream, size_t byte_stream_size, int byte_order, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_to_byte_stream "libfdata_identifier_t *identifier, uint8_t *byte_stream, size_t byte_stream_size, int byte_order, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_get_string_size "libfdata_identifier_t *identifier, size_t *string_size, uint32_t string_format_flags, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_from_utf8_string "libfdata_identifier_t *identifier, const uint8_t *utf8_string, size_t utf8_string_length, uint32_t string_format_flags, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_from_utf8_string_with_index "libfdata_identifier_t *identifier, const uint8_t *utf8_string, size_t utf8_string_length, size_t* utf8_string_index, uint32_t string_format_flags, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_to_utf8_string "libfdata_identifier_t *identifier, uint8_t *utf8_string, size_t utf8_string_size, uint32_t string_format_flags, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_to_utf8_string_with_index "libfdata_identifier_t *identifier, uint8_t *utf8_string, size_t utf8_string_size, size_t* utf8_string_index, uint32_t string_format_flags, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_from_utf16_string "libfdata_identifier_t *identifier, const uint16_t *utf16_string, size_t utf16_string_length, uint32_t string_format_flags, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_from_utf16_string_with_index "libfdata_identifier_t *identifier, const uint16_t *utf16_string, size_t utf16_string_length, size_t* utf16_string_index, uint32_t string_format_flags, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_to_utf16_string "libfdata_identifier_t *identifier, uint16_t *utf16_string, size_t utf16_string_size, uint32_t string_format_flags, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_to_utf16_string_with_index "libfdata_identifier_t *identifier, uint16_t *utf16_string, size_t utf16_string_size, size_t* utf16_string_index, uint32_t string_format_flags, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_from_utf32_string "libfdata_identifier_t *identifier, const uint32_t *utf32_string, size_t utf32_string_length, uint32_t string_format_flags, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_from_utf32_string_with_index "libfdata_identifier_t *identifier, const uint32_t *utf32_string, size_t utf32_string_length, size_t* utf32_string_index, uint32_t string_format_flags, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_to_utf32_string "libfdata_identifier_t *identifier, uint32_t *utf32_string, size_t utf32_string_size, uint32_t string_format_flags, libfdata_error_t **error"
.Ft int
.Fn libfdata_identifier_copy_to_utf32_string_with_index "libfdata_identifier_t *identifier, uint32_t *utf32_string, size_t utf32_string_size, size_t* utf32_string_index, uint32_t string_format_flags, libfdata_error_t **error"
.Sh DESCRIPTION
The
.Fn libfdata_get_version
function is used to retrieve the library version.
.Sh RETURN VALUES
Most of the functions return NULL or -1 on error, dependent on the return type. For the actual return values refer to libfdata.h
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh NOTES
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
http://code.google.com/p/libfdata/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright (c) 2010-2013, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
the libfdata.h include file
